pub mod collections;
pub mod export;
pub mod library;
pub mod metadata;
pub mod reader;
pub mod rendering;
pub mod search;
pub mod tags;

// New v2.0 commands
pub mod backup;
pub mod conversion;
pub mod cover;
pub mod debrid;
pub mod discord;
pub mod doodle;
pub mod folder_watch;
pub mod manga;
pub mod preferences;
pub mod prowlarr;
pub mod rss;
pub mod share;
pub mod sources;
pub mod torbox;
pub mod translation;

#[macro_export]
macro_rules! generate_shiori_handlers {
    () => {
        tauri::generate_handler![
            commands::library::get_books,
            commands::library::get_book_summaries,
            commands::library::get_book_summaries_by_domain,
            commands::library::find_duplicate_books,
            commands::library::get_total_books,
            commands::library::get_library_stats,
            commands::library::get_thumbnail,
            commands::library::get_recommended_books,
            commands::library::get_next_book_in_series,
            commands::library::get_book,
            commands::library::add_book,
            commands::library::update_book,
            commands::library::delete_book,
            commands::library::delete_books,
            commands::library::import_books,
            commands::library::scan_folder_unified,
            commands::library::import_manga,
            commands::library::download_gutenberg_epub,
            commands::library::download_libgen_epub,
            commands::library::scan_folder_for_manga,
            commands::library::import_comics,
            commands::library::scan_folder_for_comics,
            commands::library::start_background_scan,
            commands::library::get_books_by_domain,
            commands::library::get_total_books_by_domain,
            commands::library::reset_database,
            commands::library::update_reading_status,
            commands::library::get_books_by_reading_status,
            commands::search::search_books,
            commands::metadata::extract_metadata,
            commands::metadata::search_manga_metadata,
            commands::metadata::get_manga_metadata_by_id,
            commands::metadata::parse_manga_filename,
            commands::metadata::search_book_metadata,
            commands::metadata::search_book_by_isbn,
            commands::metadata::enrich_book_metadata,
            commands::metadata::apply_selected_metadata,
            commands::metadata::apply_selected_series_metadata,
            commands::metadata::preview_cover_url,
            commands::tags::get_tags,
            commands::tags::create_tag,
            commands::tags::add_tag_to_book,
            commands::tags::remove_tag_from_book,
            commands::reader::get_reading_progress,
            commands::reader::get_reading_progress_batch,
            commands::reader::save_reading_progress,
            commands::reader::get_annotations,
            commands::reader::create_annotation,
            commands::reader::update_annotation,
            commands::reader::delete_annotation,
            commands::reader::get_annotation_categories,
            commands::reader::create_annotation_category,
            commands::reader::update_annotation_category,
            commands::reader::delete_annotation_category,
            commands::reader::search_annotations_global,
            commands::reader::get_all_annotations,
            commands::reader::export_annotations,
            commands::reader::get_reader_settings,
            commands::reader::get_reader_startup_data,
            commands::reader::save_reader_settings,
            commands::reader::get_book_file_path,
            commands::reader::detect_book_format,
            commands::reader::validate_book_file,
            commands::reader::get_error_details,
            commands::reader::start_reading_session,
            commands::reader::end_reading_session,
            commands::reader::heartbeat_reading_session,
            commands::reader::get_daily_reading_stats,
            commands::reader::get_book_reading_stats,
            commands::reader::get_reading_streak,
            commands::reader::get_reading_goal,
            commands::reader::update_reading_goal,
            commands::reader::get_today_reading_time,
            commands::rendering::open_book_renderer,
            commands::rendering::close_book_renderer,
            commands::rendering::get_book_toc,
            commands::rendering::get_book_chapter,
            commands::rendering::get_book_chapter_count,
            commands::rendering::search_in_book,
            commands::rendering::get_epub_resource,
            commands::rendering::get_renderer_cache_stats,
            commands::rendering::clear_renderer_cache,
            commands::rendering::render_pdf_page,
            commands::rendering::get_pdf_page_dimensions,
            commands::collections::get_collections,
            commands::collections::get_collection,
            commands::collections::create_collection,
            commands::collections::update_collection,
            commands::collections::delete_collection,
            commands::collections::add_book_to_collection,
            commands::collections::remove_book_from_collection,
            commands::collections::add_books_to_collection,
            commands::collections::get_collection_books,
            commands::collections::get_nested_collections,
            commands::collections::toggle_book_favorite,
            commands::collections::get_favorite_book_ids,
            commands::collections::get_collections_by_type,
            commands::collections::preview_smart_collection,
            commands::export::export_library,
            // v2.0 commands
            commands::conversion::convert_book,
            commands::conversion::get_conversion_status,
            commands::conversion::list_conversion_jobs,
            commands::conversion::cancel_conversion,
            commands::conversion::get_supported_conversions,
            commands::conversion::check_calibre_available,
            commands::conversion::convert_with_calibre,
            commands::conversion::convert_and_replace_book,
            commands::conversion::open_book_for_reading,
            commands::conversion::book_needs_conversion,
            commands::conversion::cleanup_converted_cache,
            commands::cover::generate_cover,
            commands::cover::get_book_cover,
            commands::cover::get_book_cover_bytes,
            commands::cover::get_cover_by_id,
            commands::cover::get_cover_path_by_id,
            commands::cover::get_cover_paths_batch,
            commands::cover::clear_cover_cache,
            commands::rss::add_rss_feed,
            commands::rss::get_rss_feed,
            commands::rss::list_rss_feeds,
            commands::rss::update_rss_feed,
            commands::rss::delete_rss_feed,
            commands::rss::toggle_rss_feed,
            commands::rss::update_rss_feed_articles,
            commands::rss::update_all_rss_feeds,
            commands::rss::get_unread_articles,
            commands::rss::mark_article_read,
            commands::rss::generate_daily_epub,
            commands::rss::trigger_feed_update,
            commands::rss::trigger_daily_epub_generation,
            commands::share::create_book_share,
            commands::share::get_share,
            commands::share::is_share_valid,
            commands::share::revoke_share,
            commands::share::list_book_shares,
            commands::share::start_share_server,
            commands::share::stop_share_server,
            commands::share::is_share_server_running,
            commands::share::cleanup_expired_shares,
            // Manga reader commands
            commands::manga::open_manga,
            commands::manga::get_manga_page,
            commands::manga::get_manga_page_path,
            commands::manga::preload_manga_pages,
            commands::manga::get_manga_page_dimensions,
            commands::manga::close_manga,
            commands::manga::get_manga_series_list,
            commands::manga::get_series_volumes,
            commands::manga::auto_group_manga_volumes,
            commands::manga::create_manga_series,
            commands::manga::update_manga_series,
            commands::manga::assign_book_to_series,
            commands::manga::remove_book_from_series,
            commands::manga::delete_manga_series,
            commands::manga::merge_manga_series,
            // Preferences commands
            commands::preferences::get_user_preferences,
            commands::preferences::get_theme_sync,
            commands::preferences::update_user_preferences,
            commands::preferences::get_book_preference_overrides,
            commands::preferences::set_book_preference_override,
            commands::preferences::clear_book_preference_override,
            commands::preferences::get_manga_preference_overrides,
            commands::preferences::set_manga_preference_override,
            commands::preferences::clear_manga_preference_override,
            commands::preferences::get_onboarding_state,
            commands::preferences::get_startup_data,
            commands::preferences::complete_onboarding,
            commands::preferences::reset_onboarding,
            commands::preferences::torrent_network_get_config,
            commands::preferences::torrent_network_set_config,
            // Doodle commands
            commands::doodle::save_doodle,
            commands::doodle::get_doodle,
            commands::doodle::delete_doodle,
            commands::doodle::delete_book_doodles,
            // Backup commands
            commands::backup::create_backup,
            commands::backup::restore_backup,
            commands::backup::get_backup_info,
            // File write command
            commands::export::write_text_to_file,
            // Translation/dictionary commands
            // Discord commands
            commands::discord::discord_connect,
            commands::discord::discord_disconnect,
            commands::discord::discord_set_activity,
            commands::discord::discord_clear_activity,
            commands::translation::dictionary_lookup,
            commands::translation::translate_text,
            // Folder watch commands
            commands::folder_watch::start_folder_watch,
            commands::folder_watch::stop_folder_watch,
            commands::folder_watch::add_watch_folder,
            commands::folder_watch::remove_watch_folder,
            commands::folder_watch::get_watch_folders,
            commands::folder_watch::get_watch_status,
            commands::sources::list_sources,
            commands::sources::list_sources_by_type,
            commands::sources::plugin_search,
            commands::sources::plugin_search_with_meta,
            commands::sources::search_manga_sources,
            commands::sources::plugin_browse,
            commands::sources::plugin_get_chapters,
            commands::sources::plugin_get_pages,
            commands::sources::plugin_download_chapter,
            commands::sources::set_source_config,
            commands::sources::proxy_manga_image,
            commands::sources::toongod_get_config,
            commands::sources::toongod_set_config,
            commands::debrid::debrid_resolve_and_import,
            // Torbox commands
            commands::torbox::torbox_set_api_key,
            commands::torbox::torbox_get_api_key,
            commands::torbox::torbox_add_magnet,
            commands::torbox::torbox_get_status,
            commands::torbox::torbox_get_download_link,
            commands::torbox::torbox_download_and_import,
            // SHIORI x TORBOX commands
            commands::torbox::verify_torbox_key,
            commands::torbox::send_to_torbox,
            commands::torbox::get_torbox_instant,
            commands::torbox::add_to_torbox_queue,
            commands::torbox::save_torbox_key,
            commands::torbox::get_torbox_key,
            commands::torbox::import_from_torbox,
            commands::torbox::import_existing_torbox_target,
            commands::torbox::resolve_torbox_download,
            commands::torbox::wait_for_torbox_completion,
            // Prowlarr commands
            commands::prowlarr::test_prowlarr_connection,
            commands::prowlarr::search_prowlarr,
            commands::prowlarr::grab_prowlarr_release,
            // Cloudflare session commands
            cloudflare::commands::cf_session_status,
            cloudflare::commands::cf_solve,
            cloudflare::commands::cf_invalidate_session,
            cloudflare::commands::cf_clear_all_sessions,
            cloudflare::commands::cf_list_sessions,
            cloudflare::commands::cf_proxy_image,
        ]
    };
}
